name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: "Checkout sources"
      uses: actions/checkout@v2

    - name: "Setup JDK 11"
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven

    - name: "Run the Maven verify phase"
      run: mvn --batch-mode --update-snapshots verify

    - name: "Prepare staging"
      run: mkdir staging && cp target/*.jar staging

    - name: "Upload build"
      uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging

    - name: "Zip build reports"
      if: failure()
      run: zip -r reports.zip build/reports

    - uses: actions/upload-artifact@v1
      name: "Upload build reports"
      if: failure()
      with:
        name: reports
        path: reports.zip
